# Generated by Django 3.1.4 on 2021-01-08 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cricket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1run', models.PositiveIntegerField(default=0)),
                ('user1hit', models.PositiveIntegerField(default=0)),
                ('user1lastbat', models.PositiveIntegerField(default=0)),
                ('user1out', models.BooleanField(default=False)),
                ('user1lastball', models.PositiveIntegerField(default=0)),
                ('user2run', models.PositiveIntegerField(default=0)),
                ('user2hit', models.PositiveIntegerField(default=0)),
                ('user2lastbat', models.PositiveIntegerField(default=0)),
                ('user2out', models.BooleanField(default=False)),
                ('user2lastball', models.PositiveIntegerField(default=0)),
                ('gameend', models.BooleanField(default=False)),
                ('gameresult', models.TextField(blank=True, null=True)),
                ('user1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
